version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  # Add more services if needed (e.g., backend API, database, etc.)
